# Generated by Django 5.2.1 on 2025-06-29 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('status', models.BooleanField(default=True)),
                ('imagem_url', models.CharField(blank=True, max_length=512)),
            ],
        ),
    ]
