# Generated by Django 5.2.3 on 2025-06-29 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
        ('category', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.cliente'),
        ),
        migrations.AddField(
            model_name='clientefavoritos',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.cliente'),
        ),
        migrations.AddField(
            model_name='livro',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.categoria'),
        ),
        migrations.AddField(
            model_name='clientefavoritos',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.livro'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.livro'),
        ),
        migrations.AlterUniqueTogether(
            name='clientefavoritos',
            unique_together={('cliente', 'livro')},
        ),
    ]
