# Generated by Django 5.2.3 on 2025-06-29 19:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
        ('user', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('dt_atualizacao', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='ativo', max_length=50)),
                ('identificador', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.cliente')),
            ],
            options={
                'unique_together': {('cliente', 'status'), ('session_key', 'status')},
            },
        ),
        migrations.CreateModel(
            name='ItemCarrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.carrinho')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.livro')),
            ],
            options={
                'unique_together': {('carrinho', 'livro')},
            },
        ),
    ]
