# Generated by Django 5.2.3 on 2025-06-29 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0002_initial'),
        ('cart', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.cliente'),
        ),
        migrations.AddField(
            model_name='itemcarrinho',
            name='carrinho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.carrinho'),
        ),
        migrations.AddField(
            model_name='itemcarrinho',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.livro'),
        ),
        migrations.AlterUniqueTogether(
            name='carrinho',
            unique_together={('cliente', 'status'), ('session_key', 'status')},
        ),
        migrations.AlterUniqueTogether(
            name='itemcarrinho',
            unique_together={('carrinho', 'livro')},
        ),
    ]
