# Generated by Django 5.2.3 on 2025-06-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('imagem_url', models.CharField(max_length=512)),
                ('link_destino', models.CharField(max_length=512)),
                ('visivel', models.BooleanField(default=True)),
                ('prioridade', models.IntegerField()),
                ('posicao', models.CharField(max_length=100)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
