# Generated by Django 5.2.3 on 2025-06-29 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.cliente'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_pagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.metodopagamento'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='order.pedido'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='transporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.transporte'),
        ),
        migrations.AlterUniqueTogether(
            name='itempedido',
            unique_together={('pedido', 'livro')},
        ),
    ]
