# Generated by Django 5.2.1 on 2025-06-29 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.cliente'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.endereco'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.pedido'),
        ),
        migrations.AlterUniqueTogether(
            name='itempedido',
            unique_together={('pedido', 'livro')},
        ),
    ]
